import { useEffect, useState } from "react";
import Head from "next/head";
import AppLayout from "../components/AppLayout/index";
import Button from "../components/Button/index";
import GitHub from "../components/Icons/GitHub";
import Image from "next/image";
import { colors } from "../styles/theme";
import { loginWithGitHub, onAuthStateChanged } from "../firebase/client";

export default function Home() {
  const [user, setUser] = useState(null);
  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleClick = () => {
    loginWithGitHub()
      .then(setUser)
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <>
      <Head>
        <title>devtter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Image src="/devter-logo.png" alt="Logo" width={120} height={120} />
          <h1>Devtter</h1>
          <h2>
            Talk about development <br /> with developers
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill={colors.white} width={24} height={24} />
                Login with Github
              </Button>
            )}
            {user && user.avatar && (
              <div>
                <Image src={user.avatar} alt="user" width={50} height={50} />
                <strong>{user.username}</strong>
              </div>
            )}
          </div>
        </section>
      </AppLayout>
      <style jsx>
        {`
          section{
            display: grid;
            height: 100%;
            place-content: center;
            place-items: center;
          }

          div {
            margin-top: 16px;
          }

          h1 {
            color: ${colors.primary}
            font-weight: 800;
            margin-bottom: 16px;
          }

          h2 {
            font-size: 16px;
            color: ${colors.secondary}
          }

          a {
            color: blue;
            text-decoration: none;
          }
        `}
      </style>
    </>
  );
}
